# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ecg2GForPad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ecg2GForPad

  target 'Ecg2GForPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ecg2GForPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'pop'
pod 'YYModel'
pod 'Masonry'
pod 'MJRefresh'
pod 'YYWebImage'
pod 'AFNetworking'
pod 'MBProgressHUD'

end
